version: "3.3"

configs:
  errbot_config:
    file: ./config.py

# These are already available in swarmstack/errbot-docker/ and are examples
#  errbot_alerrtmanagerr-webex_plug:
#    file: ./local_plugins/alerrtmanagerr-webex/alerrtmanagerr.plug
#  errbot_alerrtmanagerr-webex_py:
#    file: ./local_plugins/alerrtmanagerr-webex/alerrtmanagerr.py
#
#  errbot_err-backend-cisco-webex-teams_plug:
#    file: ./local_backends/err-backend-cisco-webex-teams/CiscoWebexTeams.plug
#  errbot_err-backend-cisco-webex-teams_py:
#    file: ./local_backends/err-backend-cisco-webex-teams/CiscoWebexTeams.py

services:
  errbot:
    image: swarmstack/errbot-docker:latest
    configs:
      - source: errbot_config
        target: /err/config.py
      # These are already available in swarmstack/errbot-docker/ and are examples
      #      - source: errbot_alerrtmanagerr-webex_plug
      #        target: /err/local_plugins/alerrtmanagerr-webex/alerrtmanagerr.plug
      #      - source: errbot_alerrtmanagerr-webex_py
      #        target: /err/local_plugins/alerrtmanagerr-webex/alerrtmanagerr.py
      #
      #      - source: errbot_err-backend-cisco-webex-teams_plug
      #        target: /err/local_backends/err-backend-cisco-webex-teams/CiscoWebexTeams.plug
      #      - source: errbot_err-backend-cisco-webex-teams_py
      #        target: /err/local_backends/err-backend-cisco-webex-teams/CiscoWebexTeams.py
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
    #Add healthcheck after enabling errbot webserver
    #healthcheck:
    #  test: "/usr/bin/curl -s -I -X GET http://localhost:3141"
    #  interval: 25s
    #  timeout: 3s
    #  start-period: 30s
    ports:
      - "3141:3141"
    volumes:
      - ./local_bind_volume_dir:/err/data
